- id: doi:10.3389/fphys.2024.1374901
  title: Pathophysiology of human hearing loss associated with variants in myosins
- id: doi:10.1007/s00439-021-02304-0
  title: Human deafness-associated variants alter the dynamics of key molecules in
    hair cell stereocilia F-actin cores
- id: doi:10.1111/cge.14115
  title: "Late-onset hearing loss case associated with a heterozygous truncating\
    \ variant of <scp><i>DIAPH1</i></scp>"
- id: doi:10.1016/j.xpro.2021.100967
  title: Fast-dissociating but highly specific antibodies are novel tools in biology,
    especially useful for multiplex super-resolution microscopy
- id: doi:10.1016/j.celrep.2021.108708
  title: Semi-automated single-molecule microscopy screening of fast-dissociating
    specific antibodies directly from hybridoma cultures
- id: doi:10.1136/jmedgenet-2019-106282
  title: Differential disruption of autoinhibition and defect in assembly of cytoskeleton
    during cell division decide the fate of human<i>DIAPH1</i>-related cytoskeletopathy
- id: doi:10.1093/hmg/ddy445
  title: The phenotypic landscape of a Tbc1d24 mutant mouse includes convulsive seizures
    resembling human early infantile epileptic encephalopathy
- id: doi:10.1007/s10162-016-0607-3
  title: Quantitative Analysis of Aquaporin Expression Levels during the Development
    and Maturation of the Inner Ear
- id: doi:10.15252/emmm.201606609
  title: "Constitutive activation of DIA1 (DIAPH1) via C-terminal truncation causes\
    \ human sensorineural hearing loss"
- id: doi:10.5631/jibirin.108.375
  title: Two Cases of Spindle Cell Carcinoma of the Head and Neck
- id: doi:10.1186/1471-2202-15-66
  title: Therapeutic potential of a gamma-secretase inhibitor for hearing restoration
    in a guinea pig model with noise-induced hearing loss
- id: doi:10.1002/cm.21098
  title: "Can filament treadmilling alone account for the F-actin turnover in\
    \ lamellipodia?"
- id: doi:10.5631/jibirin.106.161
  title: Hashimoto^|^rsquo;s Thyroiditis Affect the Outcome of Fine Needle Aspiration
    Biopsy
- id: doi:10.5631/jibirin.105.431
  title: A Case of Intraosseous Cavernous Hemangioma of the Maxillary Bone
- id: doi:10.1159/000328977
  title: Early-Onset Postirradiation Sarcoma of the Tongue after Pseudotumor Phase
- id: doi:10.5631/jibirin.103.209
  title: Breast Carcinoma Metastasis to the Temporal Bone
- id: doi:10.1371/journal.pone.0004921
  title: An Order of Magnitude Faster AIP1-Associated Actin Disruption than Nucleation
    by the Arp2/3 Complex in Lamellipodia
- id: doi:10.5631/jibirin.102.673
  title: Metastasis of Retroperitoneal Leiomyosarcoma to the Thyroid and Parotid Glands
- id: doi:10.1083/jcb.200604176
  title: "Actin turnover-dependent fast dissociation of capping protein in the\
    \ dendritic nucleation actin network: evidence of frequent filament severing"
- id: doi:10.1126/science.1093923
  title: Actin Polymerization-Driven Molecular Movement of mDia1 in Living Cells
